### ISSUE TITLE
build fail ?  &  upgrade  compose version ?

### ISSUE THREAD

**Issue by CMingTseng** [ellisonchan/ComposeBird#2]
Dear Sir  

the new  compose library version  is  1.1.1 

can upgrade ?

_______________
i try  export  "SplashScreenController" as  subproject & library (aar) ( this demo  theme res  is other  res library )

the export  is  pass , i can create subproject &  aar file

but  my demo project 

dependencies {
implementation "com.ellison.flappybird.util:SplashScreenController:0.0.1"  <--- build pass
}

dependencies {
implementation project(path: ':SplashScreenController')  <--- build fail 
}

only get  error message 

Execution failed for task ':XXX:compileXXXXReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

can  help me ?

THX

**Comment by ellisonchan** [comment]
> See log for more details

Could U give me some logs.

By the way, SplashScreenController subproject will build ok?

**Comment by CMingTseng** [comment]
> > See log for more details
> 
> Could U give me some logs.
> 
> By the way, SplashScreenController subproject will build ok?

This  week  i  give a demo ?

____

other  issue 

 SplashScreenController  + theme  at Android 5  get crash !!
 
 the error   like https://github.com/alibaba/atlas/issues/101
 
     Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 0
        at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:603)
        at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6423)
        at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6592)
        at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:735)
        at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:679)
        at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:62)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:808)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at android.view.View.inflate(View.java:18435)
        at androidx.core.splashscreen.SplashScreenViewProvider$ViewImpl$_splashScreenView$2.invoke(SplashScreenViewProvider.kt:94)
        at androidx.core.splashscreen.SplashScreenViewProvider$ViewImpl$_splashScreenView$2.invoke(SplashScreenViewProvider.kt:93)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at androidx.core.splashscreen.SplashScreenViewProvider$ViewImpl.get_splashScreenView(SplashScreenViewProvider.kt:93)
        at androidx.core.splashscreen.SplashScreenViewProvider$ViewImpl.createSplashScreenView(SplashScreenViewProvider.kt:103)
        at androidx.core.splashscreen.SplashScreenViewProvider.<init>(SplashScreenViewProvider.kt:52)
        at androidx.core.splashscreen.SplashScreen$Impl.setOnExitAnimationListener(SplashScreen.kt:305)
        at androidx.core.splashscreen.SplashScreen.setOnExitAnimationListener(SplashScreen.kt:185)
        at com.pgtalk.feature.utils.SplashScreenController.customizeSplashScreenExit(SplashScreenController.kt:36)
        at com.pgtalk.feature.utils.SplashScreenController.customizeSplashScreen(SplashScreenController.kt:25)

**Comment by ellisonchan** [comment]
> SplashScreenController + theme at Android 5 get crash !!

SplashScreen does not support before Android 6.

> core-splashscreen provides backward compatibility for the new Splash Screen APIs. 
> This first alpha version contains all the new APIs **backported down to API 23**, with the exception of the icon background.

**Comment by ellisonchan** [comment]
Upgraded, so close it.
